server:
  port: 1200
spring:
  application:
    name: service-eureka
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}:${spring.application.name}
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/